apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kmashwin/argocd.git
    targetRevision: HEAD
    path: store
  destination:
    server: https://kubernetes.default.svc
    namespace: store
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
